### ISSUE TITLE
failed to install pre-commit-matlab-lint

### ISSUE THREAD

**Issue by lbbrhzn** [tcumby/pre-commit-matlab-lint#36]
I tried to install pre-commit-matlab lint, but I encounter the error below. Looks like the issue is cause by setuptools.
Any idea how to fix this?

```
[INFO] Installing environment for https://github.com/tcumby/pre-commit-matlab-lint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\xxxx.xxxx\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\python.exe', '-mvirtualenv', 'C:\\Users\\xxxx.xxxx\\.cache\\pre-commit\\repovwrbwtw5\\py_env-python3.10')
return code: 1
stdout:
    RuntimeError: failed to build image setuptools because:
    Traceback (most recent call last):
      File "C:\Users\xxxx.xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 55, in _install
        installer.install(creator.interpreter.version_info)
      File "C:\Users\xxxx.xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 35, in install
        self._sync(filename, into)
      File "C:\Users\xxxx.xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\seed\embed\via_app_data\pip_install\copy.py", line 11, in _sync
        copy(src, dst)
      File "C:\Users\xxxx.xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\util\path\_sync.py", line 37, in copy
        method(str(src), str(dest))
      File "C:\Users\xxxx.xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\virtualenv\util\path\_sync.py", line 48, in copytree
        shutil.copy(src_f, dest_f)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 417, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 254, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxx.xxxx\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\\LocalCache\\Local\\pypa\\virtualenv\\wheel\\3.10\\image\\1\\CopyPipInstall\\setuptools-67.4.0-py3-none-any\\setuptools\\config\\_validate_pyproject\\fastjsonschema_exceptions.py'
stderr: (none)
Check the log at C:\Users\xxxx.xxxx\.cache\pre-commit\pre-commit.log
```

**Comment by lbbrhzn** [comment]
.pre-commit-config.yaml:

```
- repo: https://github.com/tcumby/pre-commit-matlab-lint
  rev: v1.0.5
  hooks:
    - id: lint-matlab
      args: ["--matlab_release_name=R2022b"]
```

**Comment by tcumby** [comment]
Thanks for the error report. Can you please also attach the log file `Check the log at C:\Users\xxxx.xxxx\.cache\pre-commit\pre-commit.log`?

Would it be possible to try on another python 3.10 interpreter (i.e. a standard installer from python.org installed for all users into C:\Program Files)? My concern is that the paths are getting quite long and unless long-path awareness/support is enabled on your machine, there could be odd path related failures.
